#!/usr/bin/env sh

battery_variable=$(acpi | sed 's/Battery 0: //
	s/until charged//
	s/,//g
	s/  / /g')
echo $battery_variable

numerical_value=$(echo $battery_variable | awk '{print $2}' | sed 's/\%//')
battery_state=$(echo $battery_variable | awk '{print $1}')

case "$(echo $battery_state)" in
	"Discharging" 	)	echo "💫" ;;
	"Charging"	)	echo "⚡" ;;
	"Full"		)	echo "" ;;
esac
