#!/usr/bin/bash
# Sync mail and give notification if there is new mail.


export DISPLAY=:0.0

notify() { notify-send "mutt-wizard" "📬 $2 new mail(s) in \`$1\` account." ;}

echo " 🔃" > /tmp/imapsyncicon_$USER
pkill -RTMIN+12 i3blocks

# Run mbsync. You can feed this script different settings.
mbsync -a 
rm -f /tmp/imapsyncicon_$USER
pkill -RTMIN+12 i3blocks

# Check all accounts/mailboxes for new mail. Notify if there is new content.
for account in "$HOME/.local/share/mail/"*
do
	acc="$(echo "$account" | sed "s/.*\///")"
	newcount=$(find "$HOME/.local/share/mail/$acc/INBOX/new/" "$HOME/.local/share/mail/$acc/Inbox/new/" "$HOME/.local/share/mail/$acc/inbox/new/" -type f -newer "$HOME/.config/mutt/.mailsynclastrun" 2> /dev/null | wc -l)
	[ "$newcount" -gt "0" ] && notify-send "$acc" "$newcount" &
done
notmuch new 2>/dev/null

#Create a touch file that indicates the time of the last run of mailsync
touch "$HOME/.config/mutt/.mailsynclastrun"
