#!/bin/bash

function countdown(){
   date1=$((`date +%s` + $1*60)); 
   while [ "$date1" -ge `date +%s` ]; do 
     echo -ne "$(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r";
     sleep 0.1
   done
   
   notify-send -i /usr/share/icons/Adwaita/16x16/categories/emoji-recent-symbolic.symbolic.png $2 
play /usr/share/sounds/freedesktop/stereo/phone-incoming-call.oga
}

   while true; do
	   countdown $1 "Worktime starts"
	   countdown $2 "Break time buddy"
   done
